# Format for logging output.
# See https://docs.python.org/2/library/logging.html#logrecord-attributes
# Type: str
log_format: "%(asctime)-15s\t%(levelname)s\t%(message)s"

# Number of worker processes to fork for receving requests. This option
# is mutually exclusive with debug.
# Type: int
num_processes: 1

# The port to listen to requests on.
# Type: int
port: 8990

# The address to bind to. By default it listens on all interfaces.
# Type: string
#bind_address: "127.0.0.1"
bind_address: "0.0.0.0"

# Passing debug option down tornado. Useful for development to
# automatically reload code.
# Type: bool
debug: true

# Takes a SqlAlchemy URL to the database. More details
# can be found at the following URL:
# http://docs.sqlalchemy.org/en/rel_0_9/core/engines.html#database-urls
#
# Type: str
database: "sqlite:///nsot.sqlite"
#database: "mysql://root@ubuntu.local/nsot"

# Header to check for Authenticated Email
# Type: str
user_auth_header: "X-NSoT-Email"

# Allows you to restrict requests to certain IP addresses and/or IP networks
# specified in CIDR notation.
# Type: str or list
#restrict_networks: "127.0.0.1"

# Specifies whether to use XSRF headers/cookies for API calls. Default: true
# Type: bool
api_xsrf_enabled: false

# Secret key used to encrypt/decrypt your secure cookies
cookie_secret: "bacon1234"

# The secret key used for encryping decrypting stuff
secret_key: "fziQm7hJ8NgHZufUJNAg0GSGdVxOxu9tKvt0pxIlZzo="

# API key expiration in secs
#auth_token_expiry: 10
auth_token_expiry: 86400

# Google OAuth2 settings. You'll need to replace these with your application's
# client_id, client_secret, and redirect_uri.
#    key: CLIENT_ID
#    secret: CLIENT_SECRET
#    redirect_uri: REDIRECT_URI
# Type: dict
google_oauth:
    key: "360908405491-s01u78cqsc7ltm8on5p7o3ii40lo2f1d.apps.googleusercontent.com"
    secret: "MGjxYSR67Gt2LaqTvEXvtiWj"
    redirect_uri: "http://localhost:8990/auth/google/oauth2"

# For CLI clients
google_oauth_cli:
    client_id: "360908405491-m8r7p02u2e5l9sskp7b8f0ij6q20oaho.apps.googleusercontent.com"
    client_secret: "FuRPrzs7OWF_Gv_Qi7B9XBSW"
